### ISSUE TITLE
Remove script doesn't remove systemd daemon and don't stop it

### ISSUE THREAD

**Issue by M5oul** [YunoHost-Apps/lektor_ynh#1]
I installed then removed lektor app.
Then, I installed [Firefox Sync app](https://github.com/abeudin/ffsync_ynh).
I think it break ffsync which also use Python virtualenv.

On `https://domain.tld/ffsync/token/1.0/sync/1.5` it's displayed:
![capture du 2016-03-26 13-33-18](https://cloud.githubusercontent.com/assets/4758871/14060061/59f7af5e-f357-11e5-9558-497e9f93e0d1.png)
![capture du 2016-03-26 13-34-52](https://cloud.githubusercontent.com/assets/4758871/14060068/8fbdd8c0-f357-11e5-9a13-c5277bafc46d.png)

**Comment by Psycojoker** [comment]
Need to "undo":
- https://github.com/Psycojoker/lektor_ynh/blob/master/scripts/install#L106-L107
- https://github.com/Psycojoker/lektor_ynh/blob/master/scripts/install#L96

It also would be good to remove the user.

**Comment by M5oul** [comment]
To add in the remove script:
`sudo systemctl stop ynh-lektor`
`sudo rm -f /etc/systemd/system/ynh-lektor.service`

I think it solved the issue.

**Comment by Psycojoker** [comment]
I think that this command is missing `sudo systemctl daemon-reload`

**Comment by Psycojoker** [comment]
Fixed
